version: '3.8'

services:
  app:
    build: ./backend-app
    ports: 
      - 3000:3000
    volumes:
    - './backend-app:/app'
    - '/app/node_modules'
    depends_on:
      - mysql

  mysql:
   image: mysql:8.0
   environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'cafe_db'
      MYSQL_USER: 'sqluser'
      MYSQL_PASSWORD: 'password'
   volumes:
      - './mysql/db.init.sql:/docker-entrypoint-initdb.d/db.init.sql'